### ISSUE TITLE
Not an issue, query regarding the automation

### ISSUE THREAD

**Issue by sidd-harth** [crdant/pcf-on-gcp#3]
Hi, I am trying to setup PCF on GCP and going through available documentation on Google. I came across Terraform scripts & this automation repo. 

AFAIK Terraform scripts only automate,
1. Prepare GCP env
2. Install Ops Manager 

Does this script automate all below things?
1. Prepare GCP env
2. Install Ops Manager
3. Install Bosh Director
4. Install Elastic Runtime

So does this script automate all the above steps?
Thanks

Note- I know it is not the right medium to ask queries, but it would help me a lot and save time based on your answers.

**Comment by crdant** [comment]
Yes, the script is designed to handle all of those steps.

**Comment by sidd-harth** [comment]
Thank you for the reply.

In _prepare.sh_ I see, _echo "Preparing for Elastic Runtime installation..."_. After preparing I didn't understand if we have to install it manually or there is script for automation.

How is the Elastic Runtime installation automated? 
Does Elastic Runtime have any APIs(provided by Pivotal) to automate? (I tried looking into Pivotal docs, but couldn't find them)

**Comment by crdant** [comment]
You have to run the scripts in a sequence as shown in the README.
